In [211]:
from shapely.geometry import Point
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import folium 
import geopandas as gpd
from folium.plugins import MarkerCluster
from folium.plugins import FastMarkerCluster

In [212]:
%matplotlib inline

In [213]:
zipcodes = gpd.read_file('../data/zipcodes.geojson')

In [214]:
derecho_911=pd.read_csv('../data/Phone Calls_Derecho.csv')

In [215]:
tornado_911=pd.read_csv('../data/Phone_Calls_Tornado.csv')

In [216]:
disp_derecho=pd.read_csv('../data/Computer Aided Dispatch Data_Derecho Incidents.csv',skiprows=2)

In [217]:
disp_tornado=pd.read_csv('../data/Computer Aided Dispatch Data_Tornado Incidents.csv',skiprows=3)

In [218]:
single_f=pd.read_csv('../data/singlef2017.csv')

In [219]:
building_p=pd.read_csv('../data/Building_Permits_Issued.csv')

/Users/JMO/opt/anaconda3/envs/geospatial/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [220]:
building_p

,Permit #,Permit Type Description,Permit Subtype Description,Parcel,Date Entered,Date Issued,Construction Cost,Address,City,State,ZIP,Subdivision / Lot,Contact,Permit Type,Permit Subtype,IVR Tracking #,Purpose,Council District,Census Tract,Mapped Location
0,2019067152,Building Demolition Permit,Demolition Permit - Residential,06106005200,11/01/2019,11/01/2019,6000.0,600 MAPLEWOOD LN,NASHVILLE,TN,37216,S SIDE MAPLEWOOD LANE & W OF HUTSON AVE,CONTRERAS DESIGN BUILD LLC,CADM,CAZ01A001,3728422,to demolish existing residence and detached st...,8.0,37011002.0,"600 MAPLEWOOD LN\nNASHVILLE, TN 37216\n(36.228..."
1,2019011084,Building Use & Occupancy,"Multifamily, Townhome",051100J90000CO,02/25/2019,07/22/2019,0.0,812 BRIAR CIR,MADISON,TN,37115,COMMON AREA HOMES AT BRIAR,COLE INVESTMENTS LLC,CAUO,CAA03R301,3611315,MASTER PERMIT ONLY� � NO CONSTRUCTION� �MULTI-...,8.0,37010802.0,"812 BRIAR CIR\nMADISON, TN 37115"
2,2019011479,Building Commercial - Rehab,Restaurant (Full Service),11714005500,02/27/2019,07/22/2019,759670.0,2171 GREEN HILLS VILLAGE DR,NASHVILLE,TN,37215,W/S HILLSBORO PK. & N/S ABBOTT MARTIN RD.,"BATTINO CONTRACTING SOLUTIONS, LLC",CACR,CAF19A203,3613106,2475 sq.ft. build out of CAVA RESTURANT to inc...,25.0,37017901.0,"2171 GREEN HILLS VILLAGE DR\nNASHVILLE, TN 372..."
3,2019039568,Building Residential - New,Single Family Residence,085040A40800CO,07/03/2019,07/22/2019,300888.0,4327 STONE HALL BLVD,HERMITAGE,TN,37076,LOT 408 THE RESERVE AT STONE HALL PH 2 SEC 1,MERITAGE HOMES OF TENNESSEE INC,CARN,CAA01R301,3687554,New Single Family construction - Total Sq foot...,14.0,37015402.0,"4327 STONE HALL BLVD\nHERMITAGE, TN 37076"
4,2017009328,Building Use & Occupancy,"Accessory Structure, Pools",062020B17400CO,02/08/2017,02/08/2017,8000.0,3076 DELTA QUEEN DR,NASHVILLE,TN,37214,LOT 91 ABBINGTON PARK PH1 SEC 4,SELF CONTRACTOR RESIDENTIAL (SEE APPLICANT INF...,CAUO,CAA14U016,3318756,to install an oval in ground swimming pool wit...,15.0,37015300.0,"3076 DELTA QUEEN DR\nNASHVILLE, TN 37214\n(36...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34501,2018065491,Building Residential - Addition,Single Family Residence,08307030200,10/16/2018,10/30/2018,161540.0,2212 EASTLAND AVE,NASHVILLE,TN,37206,PT LOT 2 ROLLING ACRES,"ALFORD BUILDERS, LLC",CARA,CAA01R301,3569305,to construct 2 story addition which will add 1...,6.0,37012100.0,"2212 EASTLAND AVE\nNASHVILLE, TN 37206\n(36.18..."
34502,2017019524,Building Residential - Addition,Single Family Residence,04313027400,03/22/2017,03/22/2017,20000.0,316 CHERRY ST,MADISON,TN,37115,LOT 25 BLK C CRITTENDEN EST,SELF CONTRACTOR RESIDENTIAL (SEE APPLICANT INF...,CARA,CAA01R301,3338760,EXISTING ONE STORY HOUSE.\nTHIS PERMIT:\n1...N...,9.0,37010701.0,"316 CHERRY ST\nMADISON, TN 37115\n(36.258694, ..."
34503,2018008218,Building Commercial - Rehab,"General Office, Professional Services",03409008400,02/13/2018,04/17/2018,14000.0,131 EDENWOLD RD,MADISON,TN,37115,LOTS 18 19 PT 20 BLK A EDENWOLD CITY SUB,sergy motorny,CACR,CAD02B016,3446279,BUILDING AT 2100 SQFT WITH UNFINISH ATTIC AT A...,10.0,37010401.0,"131 EDENWOLD RD\nMADISON, TN 37115\n(36.287001..."
34504,2017044878,Building Sign Permit,Sign - Ground / Wall Signs,09306208500,07/10/2017,08/23/2017,5000.0,110 2ND AVE N,NASHVILLE,TN,37201,PT LOT 15 ORIGINAL TOWN OF NASHVILLE,GENERAL SIGN SERVICES,CASN,CAZ02A001,3384196,to erect 28SF illuminated wall sign for Famous...,19.0,37019500.0,"110 2ND AVE N\nNASHVILLE, TN 37201\n(36.162296..."
34505,2018059022,Building Residential - New,Single Family Residence,163020C32000CO,09/17/2018,09/26/2018,140813.0,1382 RURAL HILL RD 320,ANTIOCH,TN,37013,UNIT 320 AUTUMN RIDGE TOWNHOMES 3RD AMEND,R J YORK HOMES LLC,CARN,CAA01R301,3560019,TO CONSTRUCT A NEW SINGLE FAMILY UNIT AT 1250 ...,32.0,37015628.0,"1382 RURAL HILL RD 320\nANTIOCH, TN 37013\n(36..."

In [221]:
building_p=building_p.rename(columns={'Address':'Location','ZIP':'zip'})
building_p

,Permit #,Permit Type Description,Permit Subtype Description,Parcel,Date Entered,Date Issued,Construction Cost,Location,City,State,zip,Subdivision / Lot,Contact,Permit Type,Permit Subtype,IVR Tracking #,Purpose,Council District,Census Tract,Mapped Location
0,2019067152,Building Demolition Permit,Demolition Permit - Residential,06106005200,11/01/2019,11/01/2019,6000.0,600 MAPLEWOOD LN,NASHVILLE,TN,37216,S SIDE MAPLEWOOD LANE & W OF HUTSON AVE,CONTRERAS DESIGN BUILD LLC,CADM,CAZ01A001,3728422,to demolish existing residence and detached st...,8.0,37011002.0,"600 MAPLEWOOD LN\nNASHVILLE, TN 37216\n(36.228..."
1,2019011084,Building Use & Occupancy,"Multifamily, Townhome",051100J90000CO,02/25/2019,07/22/2019,0.0,812 BRIAR CIR,MADISON,TN,37115,COMMON AREA HOMES AT BRIAR,COLE INVESTMENTS LLC,CAUO,CAA03R301,3611315,MASTER PERMIT ONLY� � NO CONSTRUCTION� �MULTI-...,8.0,37010802.0,"812 BRIAR CIR\nMADISON, TN 37115"
2,2019011479,Building Commercial - Rehab,Restaurant (Full Service),11714005500,02/27/2019,07/22/2019,759670.0,2171 GREEN HILLS VILLAGE DR,NASHVILLE,TN,37215,W/S HILLSBORO PK. & N/S ABBOTT MARTIN RD.,"BATTINO CONTRACTING SOLUTIONS, LLC",CACR,CAF19A203,3613106,2475 sq.ft. build out of CAVA RESTURANT to inc...,25.0,37017901.0,"2171 GREEN HILLS VILLAGE DR\nNASHVILLE, TN 372..."
3,2019039568,Building Residential - New,Single Family Residence,085040A40800CO,07/03/2019,07/22/2019,300888.0,4327 STONE HALL BLVD,HERMITAGE,TN,37076,LOT 408 THE RESERVE AT STONE HALL PH 2 SEC 1,MERITAGE HOMES OF TENNESSEE INC,CARN,CAA01R301,3687554,New Single Family construction - Total Sq foot...,14.0,37015402.0,"4327 STONE HALL BLVD\nHERMITAGE, TN 37076"
4,2017009328,Building Use & Occupancy,"Accessory Structure, Pools",062020B17400CO,02/08/2017,02/08/2017,8000.0,3076 DELTA QUEEN DR,NASHVILLE,TN,37214,LOT 91 ABBINGTON PARK PH1 SEC 4,SELF CONTRACTOR RESIDENTIAL (SEE APPLICANT INF...,CAUO,CAA14U016,3318756,to install an oval in ground swimming pool wit...,15.0,37015300.0,"3076 DELTA QUEEN DR\nNASHVILLE, TN 37214\n(36...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34501,2018065491,Building Residential - Addition,Single Family Residence,08307030200,10/16/2018,10/30/2018,161540.0,2212 EASTLAND AVE,NASHVILLE,TN,37206,PT LOT 2 ROLLING ACRES,"ALFORD BUILDERS, LLC",CARA,CAA01R301,3569305,to construct 2 story addition which will add 1...,6.0,37012100.0,"2212 EASTLAND AVE\nNASHVILLE, TN 37206\n(36.18..."
34502,2017019524,Building Residential - Addition,Single Family Residence,04313027400,03/22/2017,03/22/2017,20000.0,316 CHERRY ST,MADISON,TN,37115,LOT 25 BLK C CRITTENDEN EST,SELF CONTRACTOR RESIDENTIAL (SEE APPLICANT INF...,CARA,CAA01R301,3338760,EXISTING ONE STORY HOUSE.\nTHIS PERMIT:\n1...N...,9.0,37010701.0,"316 CHERRY ST\nMADISON, TN 37115\n(36.258694, ..."
34503,2018008218,Building Commercial - Rehab,"General Office, Professional Services",03409008400,02/13/2018,04/17/2018,14000.0,131 EDENWOLD RD,MADISON,TN,37115,LOTS 18 19 PT 20 BLK A EDENWOLD CITY SUB,sergy motorny,CACR,CAD02B016,3446279,BUILDING AT 2100 SQFT WITH UNFINISH ATTIC AT A...,10.0,37010401.0,"131 EDENWOLD RD\nMADISON, TN 37115\n(36.287001..."
34504,2017044878,Building Sign Permit,Sign - Ground / Wall Signs,09306208500,07/10/2017,08/23/2017,5000.0,110 2ND AVE N,NASHVILLE,TN,37201,PT LOT 15 ORIGINAL TOWN OF NASHVILLE,GENERAL SIGN SERVICES,CASN,CAZ02A001,3384196,to erect 28SF illuminated wall sign for Famous...,19.0,37019500.0,"110 2ND AVE N\nNASHVILLE, TN 37201\n(36.162296..."
34505,2018059022,Building Residential - New,Single Family Residence,163020C32000CO,09/17/2018,09/26/2018,140813.0,1382 RURAL HILL RD 320,ANTIOCH,TN,37013,UNIT 320 AUTUMN RIDGE TOWNHOMES 3RD AMEND,R J YORK HOMES LLC,CARN,CAA01R301,3560019,TO CONSTRUCT A NEW SINGLE FAMILY UNIT AT 1250 ...,32.0,37015628.0,"1382 RURAL HILL RD 320\nANTIOCH, TN 37013\n(36..."

In [222]:
nes_energy=gpd.read_file('../data/NES_ZIP_Code.csv')

In [223]:
nes_energy.head(2)

,Year,Month,ZIP,Customer Type,Monthly Usage (kWh),geometry
0,2015,10,"37219\n(36.167467, -86.783669)",COMMERCIAL,216867,None
1,2015,9,"37213\n(36.167552, -86.767564)",COMMERCIAL,153407,None

In [224]:
nes_energy['zipcode']=nes_energy['ZIP'].str.split('\n').str[0]

In [225]:
nes_energy.head(2)

,Year,Month,ZIP,Customer Type,Monthly Usage (kWh),geometry,zipcode
0,2015,10,"37219\n(36.167467, -86.783669)",COMMERCIAL,216867,None,37219
1,2015,9,"37213\n(36.167552, -86.767564)",COMMERCIAL,153407,None,37213

In [226]:
nes_energy['long_lat']=nes_energy['ZIP'].str.split('\n').str[1]

In [227]:
nes_energy['long_lat']=nes_energy['ZIP'].str.split('\n').str[1]

In [228]:
nes_energy.head(2)

,Year,Month,ZIP,Customer Type,Monthly Usage (kWh),geometry,zipcode,long_lat
0,2015,10,"37219\n(36.167467, -86.783669)",COMMERCIAL,216867,None,37219,"(36.167467, -86.783669)"
1,2015,9,"37213\n(36.167552, -86.767564)",COMMERCIAL,153407,None,37213,"(36.167552, -86.767564)"

In [229]:
nes_energy['lat']=nes_energy['long_lat'].str.split(',').str[1]
nes_energy

,Year,Month,ZIP,Customer Type,Monthly Usage (kWh),geometry,zipcode,long_lat,lat
0,2015,10,"37219\n(36.167467, -86.783669)",COMMERCIAL,216867,None,37219,"(36.167467, -86.783669)",-86.783669)
1,2015,9,"37213\n(36.167552, -86.767564)",COMMERCIAL,153407,None,37213,"(36.167552, -86.767564)",-86.767564)
2,2016,4,37076,OUTDOOR LIGHTING,0,None,37076,NaN,NaN
3,2016,4,37214,COMMERCIAL,1149364,None,37214,NaN,NaN
4,2016,1,"37208\n(36.176427, -86.805176)",COMMERCIAL,939818,None,37208,"(36.176427, -86.805176)",-86.805176)
...,...,...,...,...,...,...,...,...,...
15492,2020,1,37238,COMMERCIAL,148500,None,37238,NaN,NaN
15493,2020,1,37242,COMMERCIAL,302400,None,37242,NaN,NaN
15494,2020,1,37243,COMMERCIAL,18514,None,37243,NaN,NaN
15495,2020,1,37243,COMMERCIAL,1181450,None,37243,NaN,NaN
15496,2020,1,37243,RESIDENTIAL,10538,None,37243,NaN,NaN

In [230]:
nes_energy['longa']=nes_energy['long_lat'].str.split('(').str[-1]
nes_energy

,Year,Month,ZIP,Customer Type,Monthly Usage (kWh),geometry,zipcode,long_lat,lat,longa
0,2015,10,"37219\n(36.167467, -86.783669)",COMMERCIAL,216867,None,37219,"(36.167467, -86.783669)",-86.783669),"36.167467, -86.783669)"
1,2015,9,"37213\n(36.167552, -86.767564)",COMMERCIAL,153407,None,37213,"(36.167552, -86.767564)",-86.767564),"36.167552, -86.767564)"
2,2016,4,37076,OUTDOOR LIGHTING,0,None,37076,NaN,NaN,NaN
3,2016,4,37214,COMMERCIAL,1149364,None,37214,NaN,NaN,NaN
4,2016,1,"37208\n(36.176427, -86.805176)",COMMERCIAL,939818,None,37208,"(36.176427, -86.805176)",-86.805176),"36.176427, -86.805176)"
...,...,...,...,...,...,...,...,...,...,...
15492,2020,1,37238,COMMERCIAL,148500,None,37238,NaN,NaN,NaN
15493,2020,1,37242,COMMERCIAL,302400,None,37242,NaN,NaN,NaN
15494,2020,1,37243,COMMERCIAL,18514,None,37243,NaN,NaN,NaN
15495,2020,1,37243,COMMERCIAL,1181450,None,37243,NaN,NaN,NaN
15496,2020,1,37243,RESIDENTIAL,10538,None,37243,NaN,NaN,NaN

In [231]:
nes_energy['Latitude']=nes_energy['longa'].str.split(',').str[0]
nes_energy

,Year,Month,ZIP,Customer Type,Monthly Usage (kWh),geometry,zipcode,long_lat,lat,longa,Latitude
0,2015,10,"37219\n(36.167467, -86.783669)",COMMERCIAL,216867,None,37219,"(36.167467, -86.783669)",-86.783669),"36.167467, -86.783669)",36.167467
1,2015,9,"37213\n(36.167552, -86.767564)",COMMERCIAL,153407,None,37213,"(36.167552, -86.767564)",-86.767564),"36.167552, -86.767564)",36.167552
2,2016,4,37076,OUTDOOR LIGHTING,0,None,37076,NaN,NaN,NaN,NaN
3,2016,4,37214,COMMERCIAL,1149364,None,37214,NaN,NaN,NaN,NaN
4,2016,1,"37208\n(36.176427, -86.805176)",COMMERCIAL,939818,None,37208,"(36.176427, -86.805176)",-86.805176),"36.176427, -86.805176)",36.176427
...,...,...,...,...,...,...,...,...,...,...,...
15492,2020,1,37238,COMMERCIAL,148500,None,37238,NaN,NaN,NaN,NaN
15493,2020,1,37242,COMMERCIAL,302400,None,37242,NaN,NaN,NaN,NaN
15494,2020,1,37243,COMMERCIAL,18514,None,37243,NaN,NaN,NaN,NaN
15495,2020,1,37243,COMMERCIAL,1181450,None,37243,NaN,NaN,NaN,NaN
15496,2020,1,37243,RESIDENTIAL,10538,None,37243,NaN,NaN,NaN,NaN

In [232]:
nes_energy['Longitude']=nes_energy['lat'].str.split(')').str[0]
nes_energy

,Year,Month,ZIP,Customer Type,Monthly Usage (kWh),geometry,zipcode,long_lat,lat,longa,Latitude,Longitude
0,2015,10,"37219\n(36.167467, -86.783669)",COMMERCIAL,216867,None,37219,"(36.167467, -86.783669)",-86.783669),"36.167467, -86.783669)",36.167467,-86.783669
1,2015,9,"37213\n(36.167552, -86.767564)",COMMERCIAL,153407,None,37213,"(36.167552, -86.767564)",-86.767564),"36.167552, -86.767564)",36.167552,-86.767564
2,2016,4,37076,OUTDOOR LIGHTING,0,None,37076,NaN,NaN,NaN,NaN,NaN
3,2016,4,37214,COMMERCIAL,1149364,None,37214,NaN,NaN,NaN,NaN,NaN
4,2016,1,"37208\n(36.176427, -86.805176)",COMMERCIAL,939818,None,37208,"(36.176427, -86.805176)",-86.805176),"36.176427, -86.805176)",36.176427,-86.805176
...,...,...,...,...,...,...,...,...,...,...,...,...
15492,2020,1,37238,COMMERCIAL,148500,None,37238,NaN,NaN,NaN,NaN,NaN
15493,2020,1,37242,COMMERCIAL,302400,None,37242,NaN,NaN,NaN,NaN,NaN
15494,2020,1,37243,COMMERCIAL,18514,None,37243,NaN,NaN,NaN,NaN,NaN
15495,2020,1,37243,COMMERCIAL,1181450,None,37243,NaN,NaN,NaN,NaN,NaN
15496,2020,1,37243,RESIDENTIAL,10538,None,37243,NaN,NaN,NaN,NaN,NaN

### single_f['Location1']=single_f['Location'].str.split(' ').str[0:4]
single_f

In [233]:
nes_energy.pop('ZIP')
nes_energy.pop('long_lat')
nes_energy.pop('lat')
nes_energy.pop('longa')

0        36.167467, -86.783669)
1        36.167552, -86.767564)
2                           NaN
3                           NaN
4        36.176427, -86.805176)
                  ...
15492                       NaN
15493                       NaN
15494                       NaN
15495                       NaN
15496                       NaN
Name: longa, Length: 15497, dtype: object

In [234]:
nes_energy

,Year,Month,Customer Type,Monthly Usage (kWh),geometry,zipcode,Latitude,Longitude
0,2015,10,COMMERCIAL,216867,None,37219,36.167467,-86.783669
1,2015,9,COMMERCIAL,153407,None,37213,36.167552,-86.767564
2,2016,4,OUTDOOR LIGHTING,0,None,37076,NaN,NaN
3,2016,4,COMMERCIAL,1149364,None,37214,NaN,NaN
4,2016,1,COMMERCIAL,939818,None,37208,36.176427,-86.805176
...,...,...,...,...,...,...,...,...
15492,2020,1,COMMERCIAL,148500,None,37238,NaN,NaN
15493,2020,1,COMMERCIAL,302400,None,37242,NaN,NaN
15494,2020,1,COMMERCIAL,18514,None,37243,NaN,NaN
15495,2020,1,COMMERCIAL,1181450,None,37243,NaN,NaN
15496,2020,1,RESIDENTIAL,10538,None,37243,NaN,NaN

In [235]:
single_f.head(3)

,APN,DistrictCode,Council District,AddressFullAddress,AddressCity,AddressPostalCode,2017 LAND,2017 IMPR,2017 TOTAL APPR,2017 TOTAL ASSD,FinishedArea
0,103020C01300CO,USD,24,276 WHITE BRIDGE PIKE 13,NASHVILLE,37209,10000,39600,49600,19840,567.0
1,103020C01400CO,USD,24,276 WHITE BRIDGE PIKE 14,NASHVILLE,37209,10000,45000,55000,13750,567.0
2,103020C01500CO,USD,24,276 WHITE BRIDGE PIKE 15,NASHVILLE,37209,10000,39600,49600,19840,567.0

In [236]:
single_f=single_f.rename(columns={'AddressFullAddress':'Location','AddressPostalCode':'zip'})
single_f

,APN,DistrictCode,Council District,Location,AddressCity,zip,2017 LAND,2017 IMPR,2017 TOTAL APPR,2017 TOTAL ASSD,FinishedArea
0,103020C01300CO,USD,24,276 WHITE BRIDGE PIKE 13,NASHVILLE,37209,10000,39600,49600,19840,567.0
1,103020C01400CO,USD,24,276 WHITE BRIDGE PIKE 14,NASHVILLE,37209,10000,45000,55000,13750,567.0
2,103020C01500CO,USD,24,276 WHITE BRIDGE PIKE 15,NASHVILLE,37209,10000,39600,49600,19840,567.0
3,103020C01600CO,USD,24,276 WHITE BRIDGE PIKE 16,NASHVILLE,37209,10000,45000,55000,13750,567.0
4,103020C01700CO,USD,24,276 WHITE BRIDGE PIKE 17,NASHVILLE,37209,10000,45000,55000,22000,567.0
...,...,...,...,...,...,...,...,...,...,...,...
197109,188100A12100CO,GSD,33,1709 PARK TERRACE LN,NOLENSVILLE,37135,48000,286600,334600,83650,2831.0
197110,188100A12200CO,GSD,33,1713 PARK TERRACE LN,NOLENSVILLE,37135,48000,289400,337400,84350,2774.0
197111,188100A12300CO,GSD,33,1717 PARK TERRACE LN,NOLENSVILLE,37135,48000,360800,408800,102200,3222.0
197112,188100A12400CO,GSD,33,2104 GLEN HAVEN DR,NOLENSVILLE,37135,33000,187300,220300,55075,1952.0
197113,188100A12500CO,GSD,33,2103 GLEN HAVEN DR,NOLENSVILLE,37135,48000,204700,252700,63175,2077.5

In [237]:
single_f.dtypes

APN                  object
DistrictCode         object
Council District      int64
Location             object
AddressCity          object
zip                   int64
2017 LAND             int64
2017 IMPR             int64
2017 TOTAL APPR       int64
2017 TOTAL ASSD       int64
FinishedArea        float64
dtype: object

In [238]:
eastn_zip_disp.dtypes

IncidentDate                  object
Location                      object
Latitude                     float64
Longitude                    float64
IncidentTypeDescription1      object
geometry                    geometry
index_right                    int64
zip                           object
objectid                      object
po_name                       object
shape_stlength                object
shape_starea                  object
dtype: object

In [239]:
zipcodes.head(3)

,zip,objectid,po_name,shape_stlength,shape_starea,geometry
0,37115,1,MADISON,178783.02488886821,596553400.57885742,"MULTIPOLYGON (((-86.68725 36.31821, -86.68722 ..."
1,37216,3,NASHVILLE,75820.997821400058,188884682.28344727,"MULTIPOLYGON (((-86.73451 36.23774, -86.73425 ..."
2,37204,9,NASHVILLE,93180.292250425613,200664795.51708984,"MULTIPOLYGON (((-86.77914 36.13424, -86.77923 ..."

In [240]:
disp_tornado.head(3)

,IncidentDate,Location,Latitude1,Longitude1,IncidentTypeDescription1
0,3/3/2020 12:36:34 AM,6205 COCKRILL BEND CIR,36.182002,-86.894052,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD
1,3/3/2020 12:37:24 AM,7337 COCKRILL BEND BLVD,36.175666,-86.894978,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD
2,3/3/2020 12:38:17 AM,110 TUNE AIRPORT DR,36.179299,-86.883727,STRUCTURE FIRE COMMERCIAL INDUSTRIAL

In [241]:
disp_tornado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   IncidentDate              260 non-null    object
 1   Location                  260 non-null    object
 2   Latitude1                 260 non-null    float64
 3   Longitude1                260 non-null    float64
 4   IncidentTypeDescription1  260 non-null    object
dtypes: float64(2), object(3)
memory usage: 10.3+ KB

In [242]:
disp_tornado=disp_tornado.rename(columns={'Longitude1':'Longitude','Latitude1':'Latitude'})

In [243]:
disp_derecho=disp_derecho.rename(columns={'Longitude1':'Longitude','Latitude1':'Latitude'})

In [244]:
disp_tornado['geometry'] = disp_tornado.apply(lambda x: Point((float(x.Longitude), 
                                                         float(x.Latitude))),axis=1)
disp_tornado.head(3)

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry
0,3/3/2020 12:36:34 AM,6205 COCKRILL BEND CIR,36.182002,-86.894052,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.89405212 36.18200191)
1,3/3/2020 12:37:24 AM,7337 COCKRILL BEND BLVD,36.175666,-86.894978,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.89497756999999 36.175666)
2,3/3/2020 12:38:17 AM,110 TUNE AIRPORT DR,36.179299,-86.883727,STRUCTURE FIRE COMMERCIAL INDUSTRIAL,POINT (-86.8837274 36.17929946)

In [245]:
disp_derecho['geometry'] = disp_derecho.apply(lambda x: Point((float(x.Longitude), 
                                                         float(x.Latitude))),axis=1)
disp_derecho.head(3)

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry
0,5/3/2020 4:31:07 PM,901 KENWICK CT W,36.046877,-86.962526,ELECTRICAL HAZARD,POINT (-86.96252641 36.04687715)
1,5/3/2020 4:32:18 PM,8036 ARBOR DR,36.082491,-86.940680,ELECTRICAL HAZARD,POINT (-86.94067952 36.08249081)
2,5/3/2020 4:32:23 PM,119 DUE WEST AV E,36.248029,-86.716875,NOT ALERT COPD,POINT (-86.71687484 36.24802948)

In [246]:
disp_t_geo = gpd.GeoDataFrame(disp_tornado, 
                           crs = zipcodes.crs, 
                           geometry = disp_tornado['geometry'])

In [247]:
disp_d_geo = gpd.GeoDataFrame(disp_derecho, 
                           crs = zipcodes.crs, 
                           geometry = disp_derecho['geometry'])

In [248]:
disp_t_by_zip = gpd.sjoin(disp_t_geo, zipcodes, op = 'within')

In [249]:
disp_d_by_zip = gpd.sjoin(disp_d_geo, zipcodes, op = 'within')

In [250]:
disp_t_by_zip.head(3)

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
0,3/3/2020 12:36:34 AM,6205 COCKRILL BEND CIR,36.182002,-86.894052,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.89405 36.18200),12,37209,10,NASHVILLE,310224.91345860378,1001364029.2892456
1,3/3/2020 12:37:24 AM,7337 COCKRILL BEND BLVD,36.175666,-86.894978,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.89498 36.17567),12,37209,10,NASHVILLE,310224.91345860378,1001364029.2892456
2,3/3/2020 12:38:17 AM,110 TUNE AIRPORT DR,36.179299,-86.883727,STRUCTURE FIRE COMMERCIAL INDUSTRIAL,POINT (-86.88373 36.17930),12,37209,10,NASHVILLE,310224.91345860378,1001364029.2892456

In [251]:
disp_d_by_zip.head(3)

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
0,5/3/2020 4:31:07 PM,901 KENWICK CT W,36.046877,-86.962526,ELECTRICAL HAZARD,POINT (-86.96253 36.04688),7,37221,17,NASHVILLE,241372.3112694624,1266395059.4877319
1,5/3/2020 4:32:18 PM,8036 ARBOR DR,36.082491,-86.940680,ELECTRICAL HAZARD,POINT (-86.94068 36.08249),7,37221,17,NASHVILLE,241372.3112694624,1266395059.4877319
17,5/3/2020 4:39:57 PM,8715 OLD HARDING PKE,36.012524,-87.024584,ELECTRICAL HAZARD,POINT (-87.02458 36.01252),7,37221,17,NASHVILLE,241372.3112694624,1266395059.4877319

In [252]:
disp_t_by_zip['zip'].value_counts()

37206    72
37208    59
37076    37
37214    27
37209    14
37201     7
37207     7
37115     6
37213     5
37219     5
37218     5
37205     3
37210     2
37203     2
37211     2
37216     2
37013     1
37138     1
37080     1
37217     1
37228     1
Name: zip, dtype: int64

In [292]:
disp_t_by_zip.shape

(260, 5)

In [253]:
disp_d_by_zip['zip'].value_counts()

37211    79
37076    61
37205    57
37013    56
37214    37
37215    34
37204    29
37221    27
37217    27
37210    26
37212    25
37209    25
37207    20
37203    20
37220    19
37115    15
37216    12
37208    12
37206     9
37027     8
37218     6
37138     6
37072     5
37080     3
37228     2
37219     1
37189     1
37201     1
37143     1
37232     1
Name: zip, dtype: int64

### 37211 had 79 calls was the Berry Hill Brentwood Area

### 37206/ East Nashville only had 9 calls

In [254]:
disp_t_by_zip['zip'].astype(object)

0      37209
1      37209
2      37209
17     37209
19     37209
       ...
231    37115
234    37217
236    37138
240    37228
259    37013
Name: zip, Length: 260, dtype: object

In [255]:
disp_d_by_zip['zip'].astype(object)

0      37221
1      37221
17     37221
88     37221
116    37221
       ...
409    37189
460    37232
604    37201
606    37228
610    37228
Name: zip, Length: 625, dtype: object

In [256]:
eastn_zip_disp=disp_t_by_zip[disp_t_by_zip['zip'].str.match('37206')]
eastn_zip_disp

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
38,3/3/2020 12:56:54 AM,318 RIVERSIDE DR,36.178444,-86.726244,WIRES DOWN WITH NO SMOKE OR ARCING,POINT (-86.72624 36.17844),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
...,...,...,...,...,...,...,...,...,...,...,...,...
243,3/3/2020 4:38:24 AM,NEWHALL DR / BRITTANY DR,36.176193,-86.723042,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.72304 36.17619),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
246,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
247,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
254,3/3/2020 4:51:36 AM,821 RAMSEY ST,36.177137,-86.757858,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.75786 36.17714),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [257]:
berryh_zip_disp=disp_d_by_zip[disp_d_by_zip['zip'].str.match('37211')]
berryh_zip_disp

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
18,5/3/2020 4:40:05 PM,188 THOMPSON LN,36.110859,-86.739307,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.73931 36.11086),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
28,5/3/2020 4:44:40 PM,5025 EDMONDSON PKE,36.070354,-86.735004,ELECTRICAL HAZARD,POINT (-86.73500 36.07035),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
35,5/3/2020 4:47:29 PM,HARDING PL / NOLENSVILLE PKE,36.079615,-86.726322,MVA INJURIES:,POINT (-86.72632 36.07962),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
46,5/3/2020 4:51:19 PM,OLD HICKORY BLVD / EDMONDSON PKE,36.040021,-86.743481,MVA OTHER HAZARDS,POINT (-86.74348 36.04002),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
47,5/3/2020 4:51:19 PM,OLD HICKORY BLVD / EDMONDSON PKE,36.040021,-86.743481,MVA OTHER HAZARDS,POINT (-86.74348 36.04002),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
...,...,...,...,...,...,...,...,...,...,...,...,...
554,5/3/2020 10:09:03 PM,499 SWISS AV,36.038240,-86.718917,DIFFICULTY SPEAKING BETWEEN BREATHS COPD,POINT (-86.71892 36.03824),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
569,5/3/2020 10:29:47 PM,4201 NOLENSVILLE PKE,36.076425,-86.725886,POSSIBLY DANGEROUS BODY AREA,POINT (-86.72589 36.07642),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
601,5/3/2020 11:24:58 PM,406 ENGLISH IVY DR,36.044554,-86.728514,SICK PERSON: NOT ALERT,POINT (-86.72851 36.04455),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
605,5/3/2020 11:31:14 PM,7533 LORDS CHAPEL DR,36.026834,-86.708393,GENERAL ALARM HIGH LIFE HAZARD,POINT (-86.70839 36.02683),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
612,5/3/2020 11:50:16 PM,5029 SUTER DR,36.070686,-86.737718,ELECTRICAL HAZARD,POINT (-86.73772 36.07069),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328

In [258]:
berryh_zip_disp1=disp_d_by_zip[disp_d_by_zip['zip'].str.match('37211')]
berryh_zip_disp1

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
18,5/3/2020 4:40:05 PM,188 THOMPSON LN,36.110859,-86.739307,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.73931 36.11086),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
28,5/3/2020 4:44:40 PM,5025 EDMONDSON PKE,36.070354,-86.735004,ELECTRICAL HAZARD,POINT (-86.73500 36.07035),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
35,5/3/2020 4:47:29 PM,HARDING PL / NOLENSVILLE PKE,36.079615,-86.726322,MVA INJURIES:,POINT (-86.72632 36.07962),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
46,5/3/2020 4:51:19 PM,OLD HICKORY BLVD / EDMONDSON PKE,36.040021,-86.743481,MVA OTHER HAZARDS,POINT (-86.74348 36.04002),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
47,5/3/2020 4:51:19 PM,OLD HICKORY BLVD / EDMONDSON PKE,36.040021,-86.743481,MVA OTHER HAZARDS,POINT (-86.74348 36.04002),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
...,...,...,...,...,...,...,...,...,...,...,...,...
554,5/3/2020 10:09:03 PM,499 SWISS AV,36.038240,-86.718917,DIFFICULTY SPEAKING BETWEEN BREATHS COPD,POINT (-86.71892 36.03824),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
569,5/3/2020 10:29:47 PM,4201 NOLENSVILLE PKE,36.076425,-86.725886,POSSIBLY DANGEROUS BODY AREA,POINT (-86.72589 36.07642),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
601,5/3/2020 11:24:58 PM,406 ENGLISH IVY DR,36.044554,-86.728514,SICK PERSON: NOT ALERT,POINT (-86.72851 36.04455),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
605,5/3/2020 11:31:14 PM,7533 LORDS CHAPEL DR,36.026834,-86.708393,GENERAL ALARM HIGH LIFE HAZARD,POINT (-86.70839 36.02683),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
612,5/3/2020 11:50:16 PM,5029 SUTER DR,36.070686,-86.737718,ELECTRICAL HAZARD,POINT (-86.73772 36.07069),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328

In [259]:
berryh_zip_disp2=disp_d_by_zip[disp_d_by_zip['zip'].str.match('37211')]
berryh_zip_disp2

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
18,5/3/2020 4:40:05 PM,188 THOMPSON LN,36.110859,-86.739307,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.73931 36.11086),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
28,5/3/2020 4:44:40 PM,5025 EDMONDSON PKE,36.070354,-86.735004,ELECTRICAL HAZARD,POINT (-86.73500 36.07035),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
35,5/3/2020 4:47:29 PM,HARDING PL / NOLENSVILLE PKE,36.079615,-86.726322,MVA INJURIES:,POINT (-86.72632 36.07962),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
46,5/3/2020 4:51:19 PM,OLD HICKORY BLVD / EDMONDSON PKE,36.040021,-86.743481,MVA OTHER HAZARDS,POINT (-86.74348 36.04002),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
47,5/3/2020 4:51:19 PM,OLD HICKORY BLVD / EDMONDSON PKE,36.040021,-86.743481,MVA OTHER HAZARDS,POINT (-86.74348 36.04002),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
...,...,...,...,...,...,...,...,...,...,...,...,...
554,5/3/2020 10:09:03 PM,499 SWISS AV,36.038240,-86.718917,DIFFICULTY SPEAKING BETWEEN BREATHS COPD,POINT (-86.71892 36.03824),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
569,5/3/2020 10:29:47 PM,4201 NOLENSVILLE PKE,36.076425,-86.725886,POSSIBLY DANGEROUS BODY AREA,POINT (-86.72589 36.07642),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
601,5/3/2020 11:24:58 PM,406 ENGLISH IVY DR,36.044554,-86.728514,SICK PERSON: NOT ALERT,POINT (-86.72851 36.04455),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
605,5/3/2020 11:31:14 PM,7533 LORDS CHAPEL DR,36.026834,-86.708393,GENERAL ALARM HIGH LIFE HAZARD,POINT (-86.70839 36.02683),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
612,5/3/2020 11:50:16 PM,5029 SUTER DR,36.070686,-86.737718,ELECTRICAL HAZARD,POINT (-86.73772 36.07069),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328

In [260]:
berryh_zip_disp3=disp_d_by_zip[disp_d_by_zip['zip'].str.match('37211')]
berryh_zip_disp3

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
18,5/3/2020 4:40:05 PM,188 THOMPSON LN,36.110859,-86.739307,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.73931 36.11086),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
28,5/3/2020 4:44:40 PM,5025 EDMONDSON PKE,36.070354,-86.735004,ELECTRICAL HAZARD,POINT (-86.73500 36.07035),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
35,5/3/2020 4:47:29 PM,HARDING PL / NOLENSVILLE PKE,36.079615,-86.726322,MVA INJURIES:,POINT (-86.72632 36.07962),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
46,5/3/2020 4:51:19 PM,OLD HICKORY BLVD / EDMONDSON PKE,36.040021,-86.743481,MVA OTHER HAZARDS,POINT (-86.74348 36.04002),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
47,5/3/2020 4:51:19 PM,OLD HICKORY BLVD / EDMONDSON PKE,36.040021,-86.743481,MVA OTHER HAZARDS,POINT (-86.74348 36.04002),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
...,...,...,...,...,...,...,...,...,...,...,...,...
554,5/3/2020 10:09:03 PM,499 SWISS AV,36.038240,-86.718917,DIFFICULTY SPEAKING BETWEEN BREATHS COPD,POINT (-86.71892 36.03824),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
569,5/3/2020 10:29:47 PM,4201 NOLENSVILLE PKE,36.076425,-86.725886,POSSIBLY DANGEROUS BODY AREA,POINT (-86.72589 36.07642),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
601,5/3/2020 11:24:58 PM,406 ENGLISH IVY DR,36.044554,-86.728514,SICK PERSON: NOT ALERT,POINT (-86.72851 36.04455),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
605,5/3/2020 11:31:14 PM,7533 LORDS CHAPEL DR,36.026834,-86.708393,GENERAL ALARM HIGH LIFE HAZARD,POINT (-86.70839 36.02683),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
612,5/3/2020 11:50:16 PM,5029 SUTER DR,36.070686,-86.737718,ELECTRICAL HAZARD,POINT (-86.73772 36.07069),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328

In [261]:
berryh_zip_disp4=disp_d_by_zip[disp_d_by_zip['zip'].str.match('37211')]
berryh_zip_disp4

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
18,5/3/2020 4:40:05 PM,188 THOMPSON LN,36.110859,-86.739307,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.73931 36.11086),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
28,5/3/2020 4:44:40 PM,5025 EDMONDSON PKE,36.070354,-86.735004,ELECTRICAL HAZARD,POINT (-86.73500 36.07035),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
35,5/3/2020 4:47:29 PM,HARDING PL / NOLENSVILLE PKE,36.079615,-86.726322,MVA INJURIES:,POINT (-86.72632 36.07962),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
46,5/3/2020 4:51:19 PM,OLD HICKORY BLVD / EDMONDSON PKE,36.040021,-86.743481,MVA OTHER HAZARDS,POINT (-86.74348 36.04002),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
47,5/3/2020 4:51:19 PM,OLD HICKORY BLVD / EDMONDSON PKE,36.040021,-86.743481,MVA OTHER HAZARDS,POINT (-86.74348 36.04002),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
...,...,...,...,...,...,...,...,...,...,...,...,...
554,5/3/2020 10:09:03 PM,499 SWISS AV,36.038240,-86.718917,DIFFICULTY SPEAKING BETWEEN BREATHS COPD,POINT (-86.71892 36.03824),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
569,5/3/2020 10:29:47 PM,4201 NOLENSVILLE PKE,36.076425,-86.725886,POSSIBLY DANGEROUS BODY AREA,POINT (-86.72589 36.07642),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
601,5/3/2020 11:24:58 PM,406 ENGLISH IVY DR,36.044554,-86.728514,SICK PERSON: NOT ALERT,POINT (-86.72851 36.04455),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
605,5/3/2020 11:31:14 PM,7533 LORDS CHAPEL DR,36.026834,-86.708393,GENERAL ALARM HIGH LIFE HAZARD,POINT (-86.70839 36.02683),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
612,5/3/2020 11:50:16 PM,5029 SUTER DR,36.070686,-86.737718,ELECTRICAL HAZARD,POINT (-86.73772 36.07069),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328

In [262]:
eastn_zip_disp2=disp_t_by_zip[disp_t_by_zip['zip'].str.match('37206')]
eastn_zip_disp2

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
38,3/3/2020 12:56:54 AM,318 RIVERSIDE DR,36.178444,-86.726244,WIRES DOWN WITH NO SMOKE OR ARCING,POINT (-86.72624 36.17844),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
...,...,...,...,...,...,...,...,...,...,...,...,...
243,3/3/2020 4:38:24 AM,NEWHALL DR / BRITTANY DR,36.176193,-86.723042,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.72304 36.17619),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
246,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
247,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
254,3/3/2020 4:51:36 AM,821 RAMSEY ST,36.177137,-86.757858,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.75786 36.17714),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [263]:
eastn_zip_disp3=disp_t_by_zip[disp_t_by_zip['zip'].str.match('37206')]
eastn_zip_disp3

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
38,3/3/2020 12:56:54 AM,318 RIVERSIDE DR,36.178444,-86.726244,WIRES DOWN WITH NO SMOKE OR ARCING,POINT (-86.72624 36.17844),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
...,...,...,...,...,...,...,...,...,...,...,...,...
243,3/3/2020 4:38:24 AM,NEWHALL DR / BRITTANY DR,36.176193,-86.723042,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.72304 36.17619),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
246,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
247,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
254,3/3/2020 4:51:36 AM,821 RAMSEY ST,36.177137,-86.757858,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.75786 36.17714),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [264]:
eastn_zip_disp4=disp_t_by_zip[disp_t_by_zip['zip'].str.match('37206')]
eastn_zip_disp4

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
38,3/3/2020 12:56:54 AM,318 RIVERSIDE DR,36.178444,-86.726244,WIRES DOWN WITH NO SMOKE OR ARCING,POINT (-86.72624 36.17844),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
...,...,...,...,...,...,...,...,...,...,...,...,...
243,3/3/2020 4:38:24 AM,NEWHALL DR / BRITTANY DR,36.176193,-86.723042,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.72304 36.17619),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
246,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
247,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
254,3/3/2020 4:51:36 AM,821 RAMSEY ST,36.177137,-86.757858,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.75786 36.17714),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [265]:
eastn_zip_disp5=disp_t_by_zip[disp_t_by_zip['zip'].str.match('37206')]
eastn_zip_disp5

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
38,3/3/2020 12:56:54 AM,318 RIVERSIDE DR,36.178444,-86.726244,WIRES DOWN WITH NO SMOKE OR ARCING,POINT (-86.72624 36.17844),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
...,...,...,...,...,...,...,...,...,...,...,...,...
243,3/3/2020 4:38:24 AM,NEWHALL DR / BRITTANY DR,36.176193,-86.723042,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.72304 36.17619),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
246,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
247,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
254,3/3/2020 4:51:36 AM,821 RAMSEY ST,36.177137,-86.757858,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.75786 36.17714),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [266]:
eastn_zip_disp6=disp_t_by_zip[disp_t_by_zip['zip'].str.match('37206')]
eastn_zip_disp6

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
38,3/3/2020 12:56:54 AM,318 RIVERSIDE DR,36.178444,-86.726244,WIRES DOWN WITH NO SMOKE OR ARCING,POINT (-86.72624 36.17844),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
...,...,...,...,...,...,...,...,...,...,...,...,...
243,3/3/2020 4:38:24 AM,NEWHALL DR / BRITTANY DR,36.176193,-86.723042,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.72304 36.17619),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
246,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
247,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
254,3/3/2020 4:51:36 AM,821 RAMSEY ST,36.177137,-86.757858,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.75786 36.17714),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [267]:
eastn_zip_disp7=disp_t_by_zip[disp_t_by_zip['zip'].str.match('37206')]
eastn_zip_disp7

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
38,3/3/2020 12:56:54 AM,318 RIVERSIDE DR,36.178444,-86.726244,WIRES DOWN WITH NO SMOKE OR ARCING,POINT (-86.72624 36.17844),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
...,...,...,...,...,...,...,...,...,...,...,...,...
243,3/3/2020 4:38:24 AM,NEWHALL DR / BRITTANY DR,36.176193,-86.723042,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.72304 36.17619),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
246,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
247,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
254,3/3/2020 4:51:36 AM,821 RAMSEY ST,36.177137,-86.757858,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.75786 36.17714),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [268]:
eastn_zip_disp8=disp_t_by_zip[disp_t_by_zip['zip'].str.match('37206')]
eastn_zip_disp8

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
38,3/3/2020 12:56:54 AM,318 RIVERSIDE DR,36.178444,-86.726244,WIRES DOWN WITH NO SMOKE OR ARCING,POINT (-86.72624 36.17844),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
...,...,...,...,...,...,...,...,...,...,...,...,...
243,3/3/2020 4:38:24 AM,NEWHALL DR / BRITTANY DR,36.176193,-86.723042,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.72304 36.17619),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
246,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
247,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
254,3/3/2020 4:51:36 AM,821 RAMSEY ST,36.177137,-86.757858,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.75786 36.17714),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [269]:
eastn_zip_disp9=disp_t_by_zip[disp_t_by_zip['zip'].str.match('37206')]
eastn_zip_disp9

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
38,3/3/2020 12:56:54 AM,318 RIVERSIDE DR,36.178444,-86.726244,WIRES DOWN WITH NO SMOKE OR ARCING,POINT (-86.72624 36.17844),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
...,...,...,...,...,...,...,...,...,...,...,...,...
243,3/3/2020 4:38:24 AM,NEWHALL DR / BRITTANY DR,36.176193,-86.723042,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.72304 36.17619),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
246,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
247,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
254,3/3/2020 4:51:36 AM,821 RAMSEY ST,36.177137,-86.757858,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.75786 36.17714),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

### nes_energy['zipcode'].value_counts()

### nes_energy=nes_energy[nes_energy['zipcode'].str.match('37206')]
nes_energy

###nes_energy_res=nes_energy[nes_energy['Customer Type'].str.match("RESIDENTIAL")] 
nes_energy_res

#### nes_energy_comm=nes_energy[nes_energy['Customer Type'].str.match("COMMERCIAL")] 
nes_energy_comm

###disp_t_by_zip[disp_t_by_zip['IncidentTypeDescription1'].str.contain('_INDUSTRIAL_')] 
disp_t_by_zip

In [270]:
eastn_zip_disp=eastn_zip_disp[eastn_zip_disp
                    ['IncidentTypeDescription1'].str.contains('INDUSTRIAL')] 
eastn_zip_disp

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
130,3/3/2020 2:01:52 AM,2658 BARCLAY DR,36.174243,-86.719824,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.71982 36.17424),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
147,3/3/2020 2:08:08 AM,1121 RUSSELL ST,36.175354,-86.749853,SMOKE DETECTOR ALARM COMMERCIAL INDUSTRIAL B...,POINT (-86.74985 36.17535),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
152,3/3/2020 2:09:46 AM,1601 HOLLY ST,36.175831,-86.741682,SMOKE DETECTOR ALARM COMMERCIAL INDUSTRIAL B...,POINT (-86.74168 36.17583),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
154,3/3/2020 2:10:45 AM,1021 RUSSELL ST,36.175940,-86.750410,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75041 36.17594),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
155,3/3/2020 2:10:45 AM,1021 RUSSELL ST,36.175940,-86.750410,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75041 36.17594),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [271]:
berryh_zip_disp=berryh_zip_disp[berryh_zip_disp
                                ['IncidentTypeDescription1'].str.contains('INDUSTRIAL')] 
berryh_zip_disp

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
18,5/3/2020 4:40:05 PM,188 THOMPSON LN,36.110859,-86.739307,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.73931 36.11086),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
494,5/3/2020 9:04:37 PM,3112 NOLENSVILLE PKE,36.102919,-86.740745,CARBON MONOXIDE ALARM COMMERCIAL INDUSTRIAL ...,POINT (-86.74074 36.10292),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328

In [272]:
berryh_zip_disp1=berryh_zip_disp1[berryh_zip_disp1
                                  ['IncidentTypeDescription1'].str.contains('SMALL')] 
berryh_zip_disp1

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
203,5/3/2020 6:09:51 PM,212 MELMACK DR,36.073491,-86.695537,SMALL BUILDING INVESTIGATION,POINT (-86.69554 36.07349),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
204,5/3/2020 6:09:51 PM,212 MELMACK DR,36.073491,-86.695537,SMALL BUILDING INVESTIGATION,POINT (-86.69554 36.07349),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328

In [273]:
berryh_zip_disp2=berryh_zip_disp2[berryh_zip_disp2
                                  ['IncidentTypeDescription1'].str.contains('LARGE')] 
berryh_zip_disp2

Empty GeoDataFrame
Columns: [IncidentDate, Location, Latitude, Longitude, IncidentTypeDescription1, geometry, index_right, zip, objectid, po_name, shape_stlength, shape_starea]
Index: []

In [274]:
berryh_zip_disp4=berryh_zip_disp4[berryh_zip_disp4
                                  ['IncidentTypeDescription1'].str.contains('RESIDENTIAL')] 
berryh_zip_disp4

Empty GeoDataFrame
Columns: [IncidentDate, Location, Latitude, Longitude, IncidentTypeDescription1, geometry, index_right, zip, objectid, po_name, shape_stlength, shape_starea]
Index: []

In [275]:
berryh_zip_disp3=berryh_zip_disp3[berryh_zip_disp3
                     ['IncidentTypeDescription1'].str.contains('ELECTRICAL HAZARD')] 
berryh_zip_disp3

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
28,5/3/2020 4:44:40 PM,5025 EDMONDSON PKE,36.070354,-86.735004,ELECTRICAL HAZARD,POINT (-86.73500 36.07035),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
50,5/3/2020 4:52:45 PM,4900 DANBY DR,36.074124,-86.745657,ELECTRICAL HAZARD,POINT (-86.74566 36.07412),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
71,5/3/2020 5:04:57 PM,1008 ANTIOCH PKE,36.099735,-86.716167,ELECTRICAL HAZARD,POINT (-86.71617 36.09974),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
82,5/3/2020 5:10:04 PM,5101 HARDING PL,36.089220,-86.687377,ELECTRICAL HAZARD,POINT (-86.68738 36.08922),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
103,5/3/2020 5:18:01 PM,415 TUSCULUM RD,36.058491,-86.717904,ELECTRICAL HAZARD,POINT (-86.71790 36.05849),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
104,5/3/2020 5:18:01 PM,415 TUSCULUM RD,36.058491,-86.717904,ELECTRICAL HAZARD,POINT (-86.71790 36.05849),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
110,5/3/2020 5:20:40 PM,502 PATTERSON ST,36.103216,-86.745160,ELECTRICAL HAZARD,POINT (-86.74516 36.10322),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
129,5/3/2020 5:32:26 PM,SUGAR VALLEY DR / NOLENSVILLE PKE,36.015389,-86.705671,ELECTRICAL HAZARD,POINT (-86.70567 36.01539),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
153,5/3/2020 5:46:24 PM,534 NORTHCREST DR,36.066811,-86.726106,ELECTRICAL HAZARD,POINT (-86.72611 36.06681),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
159,5/3/2020 5:48:55 PM,523 HARDING PL,36.076473,-86.734832,ELECTRICAL HAZARD,POINT (-86.73483 36.07647),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
162,5/3/2020 5:50:26 PM,441 HARDING PL,36.077934,-86.730648,ELECTRICAL HAZARD,POINT (-86.73065 36.07793),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
165,5/3/2020 5:51:59 PM,141 NEESE DR,36.107389,-86.725359,ELECTRICAL HAZARD,POINT (-86.72536 36.10739),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
167,5/3/2020 5:52:33 PM,500 PARAGON MILLS RD,36.087321,-86.724044,ELECTRICAL HAZARD,POINT (-86.72404 36.08732),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
170,5/3/2020 5:53:54 PM,5004 MILLERWOOD DR,36.062963,-86.721203,ELECTRICAL HAZARD,POINT (-86.72120 36.06296),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
175,5/3/2020 5:55:32 PM,BARNES RD / NOLENSVILLE PKE,36.033535,-86.712987,ELECTRICAL HAZARD,POINT (-86.71299 36.03353),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
182,5/3/2020 5:58:50 PM,721 ASHFIELD CT,36.046381,-86.735819,ELECTRICAL HAZARD,POINT (-86.73582 36.04638),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
183,5/3/2020 5:59:05 PM,5020 MANUEL DR,36.067554,-86.752003,ELECTRICAL HAZARD,POINT (-86.75200 36.06755),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
196,5/3/2020 6:07:09 PM,357 GILLETTE RD,36.061122,-86.708744,ELECTRICAL HAZARD,POINT (-86.70874 36.06112),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
232,5/3/2020 6:26:59 PM,2512 NOLENSVILLE PKE,36.118509,-86.748643,ELECTRICAL HAZARD,POINT (-86.74864 36.11851),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
235,5/3/2020 6:30:16 PM,553 HARDING PL,36.077005,-86.739281,ELECTRICAL HAZARD,POINT (-86.73928 36.07701),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
265,5/3/2020 6:43:53 PM,236 BLACKMAN RD,36.074532,-86.736566,ELECTRICAL HAZARD,POINT (-86.73657 36.07453),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
268,5/3/2020 6:44:52 PM,271 HOLT HILLS RD,36.026908,-86.725115,ELECTRICAL HAZARD,POINT (-86.72511 36.02691),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
272,5/3/2020 6:47:50 PM,433 CEDARVIEW DR,36.042079,-86.704050,ELECTRICAL HAZARD,POINT (-86.70405 36.04208),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
280,5/3/2020 6:51:35 PM,1253 BRENTWOOD HIGHLANDS DR,36.034890,-86.716633,ELECTRICAL HAZARD,POINT (-86.71663 36.03489),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
288,5/3/2020 6:55:20 PM,5600 COUNTRY DR,36.047484,-86.707715,ELECTRICAL HAZARD,POINT (-86.70772 36.04748),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
289,5/3/2020 6:55:28 PM,3716 BAKERTOWN RD,36.076226,-86.692406,ELECTRICAL HAZARD,POINT (-86.69241 36.07623),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
302,5/3/2020 7:02:56 PM,512 RADNOR ST,36.105456,-86.745878,ELECTRICAL HAZARD,POINT (-86.74588 36.10546),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
340,5/3/2020 7:18:24 PM,3625 FLORAL DR,36.095884,-86.734727,ELECTRICAL HAZARD,POINT (-86.73473 36.09588),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
343,5/3/2020 7:20:20 PM,209 WAUFORD DR,36.075017,-86.738967,ELECTRICAL HAZARD,POINT (-86.73897 36.07502),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
347,5/3/2020 7:21:22 PM,5002 LEWISDALE CT,36.065685,-86.724326,ELECTRICAL HAZARD,POINT (-86.72433 36.06568),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
361,5/3/2020 7:27:50 PM,3100 WINGATE AV,36.104718,-86.734431,ELECTRICAL HAZARD,POINT (-86.73443 36.10472),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
380,5/3/2020 7:42:27 PM,184 ANTIOCH PKE,36.101256,-86.731892,ELECTRICAL HAZARD - WIRES DOWN,POINT (-86.73189 36.10126),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
386,5/3/2020 7:44:51 PM,4727 W LONGDALE DR,36.077539,-86.746045,ELECTRICAL HAZARD,POINT (-86.74605 36.07754),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
389,5/3/2020 7:48:02 PM,15354 OLD HICKORY BLVD,36.041237,-86.728542,ELECTRICAL HAZARD,POINT (-86.72854 36.04124),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
390,5/3/2020 7:48:02 PM,15354 OLD HICKORY BLVD,36.041237,-86.728542,ELECTRICAL HAZARD,POINT (-86.72854 36.04124),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
391,5/3/2020 7:48:32 PM,3733 WHARTON DR,36.075333,-86.690413,ELECTRICAL HAZARD,POINT (-86.69041 36.07533),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
398,5/3/2020 7:53:26 PM,233 HAYWOOD LN,36.069622,-86.697933,ELECTRICAL HAZARD,POINT (-86.69793 36.06962),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
402,5/3/2020 7:54:36 PM,3342 EZELL RD,36.079024,-86.689428,ELECTRICAL HAZARD,POINT (-86.68943 36.07902),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
405,5/3/2020 7:57:31 PM,455 SWISS AV,36.041852,-86.717646,ELECTRICAL HAZARD,POINT (-86.71765 36.04185),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
406,5/3/2020 7:59:01 PM,357 GILLETTE RD,36.061122,-86.708744,ELECTRICAL HAZARD,POINT (-86.70874 36.06112),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
408,5/3/2020 8:00:04 PM,487 ELLENWOOD DR,36.058035,-86.733791,ELECTRICAL HAZARD,POINT (-86.73379 36.05804),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
411,5/3/2020 8:02:45 PM,5017 MAYWOOD DR,36.070287,-86.757398,ELECTRICAL HAZARD,POINT (-86.75740 36.07029),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
423,5/3/2020 8:12:15 PM,5044 MARC DR,36.027227,-86.738349,ELECTRICAL HAZARD,POINT (-86.73835 36.02723),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
434,5/3/2020 8:18:32 PM,3809 CHAMBERS DR,36.070417,-86.707777,ELECTRICAL HAZARD,POINT (-86.70778 36.07042),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
461,5/3/2020 8:40:48 PM,326 PARAGON MILLS RD,36.088332,-86.716258,ELECTRICAL HAZARD,POINT (-86.71626 36.08833),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
463,5/3/2020 8:41:39 PM,309 LUNA DR,36.080271,-86.692733,ELECTRICAL HAZARD,POINT (-86.69273 36.08027),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
467,5/3/2020 8:43:52 PM,356 MELPAR DR,36.065181,-86.708691,ELECTRICAL HAZARD,POINT (-86.70869 36.06518),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
481,5/3/2020 8:54:18 PM,399 COVENTRY DR,36.078901,-86.731524,ELECTRICAL HAZARD,POINT (-86.73152 36.07890),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
538,5/3/2020 9:49:07 PM,533 ELGIN ST,36.100056,-86.746217,ELECTRICAL HAZARD,POINT (-86.74622 36.10006),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
551,5/3/2020 10:02:34 PM,313 CEDARCREEK DR,36.035265,-86.705699,ELECTRICAL HAZARD,POINT (-86.70570 36.03526),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328
612,5/3/2020 11:50:16 PM,5029 SUTER DR,36.070686,-86.737718,ELECTRICAL HAZARD,POINT (-86.73772 36.07069),49,37211,39,NASHVILLE,290587.58467925159,602215091.79736328

In [276]:
berryh_zip_disp3.shape

(51, 12)

In [277]:
eastn_zip_disp.shape ##9 locations with the word "Industrial"

(9, 12)

In [278]:
eastn_zip_disp2=eastn_zip_disp2[eastn_zip_disp2['IncidentTypeDescription1'].str.contains('ENTRAPMENT')] 
eastn_zip_disp2

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
44,3/3/2020 1:00:26 AM,30 MCFERRIN AV,36.177223,-86.755607,UNCONFIRMED ENTRAPMENT LARGE BUIDING,POINT (-86.75561 36.17722),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
65,3/3/2020 1:21:08 AM,263 RIVERSIDE DR,36.175509,-86.726167,CONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.72617 36.17551),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
67,3/3/2020 1:24:30 AM,201 N 8TH ST,36.176660,-86.758987,CONFIRMED ENTRAPMENT LARGE BUILDING,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
141,3/3/2020 2:05:40 AM,30 MCFERRIN AV,36.177223,-86.755607,UNCONFIRMED ENTRAPMENT LARGE BUIDING,POINT (-86.75561 36.17722),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
151,3/3/2020 2:09:44 AM,1111 FATHERLAND ST,36.174522,-86.749138,CONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.74914 36.17452),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [279]:
eastn_zip_disp2.shape

(6, 12)

In [280]:
eastn_zip_disp3=eastn_zip_disp3[eastn_zip_disp3
                                ['IncidentTypeDescription1'].str.contains('SMALL')] 
eastn_zip_disp3

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
45,3/3/2020 1:00:50 AM,2410 LAZENBY DR,36.174563,-86.720556,SMALL BUILDING INVESTIGATION,POINT (-86.72056 36.17456),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
65,3/3/2020 1:21:08 AM,263 RIVERSIDE DR,36.175509,-86.726167,CONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.72617 36.17551),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
151,3/3/2020 2:09:44 AM,1111 FATHERLAND ST,36.174522,-86.749138,CONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.74914 36.17452),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
198,3/3/2020 3:02:28 AM,106 S 14TH ST,36.175312,-86.746411,SMALL BUILDING INVESTIGATION,POINT (-86.74641 36.17531),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
199,3/3/2020 3:05:55 AM,107 NEILL AV,36.177420,-86.758249,SMALL BUILDING INVESTIGATION,POINT (-86.75825 36.17742),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
200,3/3/2020 3:07:40 AM,1111 FATHERLAND ST,36.174522,-86.749138,UNCONFIRMED ENTRAP SMALL BUILDING WITH HAZMAT,POINT (-86.74914 36.17452),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [281]:
eastn_zip_disp3.shape

(7, 12)

In [282]:
eastn_zip_disp4=eastn_zip_disp4[eastn_zip_disp4
                                ['IncidentTypeDescription1'].str.contains('LARGE')] 
eastn_zip_disp4

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
44,3/3/2020 1:00:26 AM,30 MCFERRIN AV,36.177223,-86.755607,UNCONFIRMED ENTRAPMENT LARGE BUIDING,POINT (-86.75561 36.17722),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
67,3/3/2020 1:24:30 AM,201 N 8TH ST,36.176660,-86.758987,CONFIRMED ENTRAPMENT LARGE BUILDING,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
141,3/3/2020 2:05:40 AM,30 MCFERRIN AV,36.177223,-86.755607,UNCONFIRMED ENTRAPMENT LARGE BUIDING,POINT (-86.75561 36.17722),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

In [283]:
eastn_zip_disp4.shape

(3, 12)

### About 10 disp calls (Small:7/Large:3) were Residential and 9 were Industrial/Commercial

### I tried searching by words such as "Apartment" or "House" but could not find any rows from the 37206 area that contained them

In [284]:
eastn_zip_disp5=eastn_zip_disp5[~eastn_zip_disp5['IncidentTypeDescription1'].str.contains('LARGE')] 
eastn_zip_disp5

,IncidentDate,Location,Latitude,Longitude,IncidentTypeDescription1,geometry,index_right,zip,objectid,po_name,shape_stlength,shape_starea
24,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
25,3/3/2020 12:47:35 AM,900 MAIN ST,36.175902,-86.757023,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75702 36.17590),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
29,3/3/2020 12:50:46 AM,201 N 8TH ST,36.176660,-86.758987,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.75899 36.17666),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
36,3/3/2020 12:55:04 AM,1809 RUSSELL ST,36.174220,-86.737600,UNCONFIRMED ENTRAPMENT SMALL BUILDING,POINT (-86.73760 36.17422),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
38,3/3/2020 12:56:54 AM,318 RIVERSIDE DR,36.178444,-86.726244,WIRES DOWN WITH NO SMOKE OR ARCING,POINT (-86.72624 36.17844),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
...,...,...,...,...,...,...,...,...,...,...,...,...
243,3/3/2020 4:38:24 AM,NEWHALL DR / BRITTANY DR,36.176193,-86.723042,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.72304 36.17619),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
246,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
247,3/3/2020 4:43:33 AM,S 18TH ST / HOLLY ST,36.175125,-86.738319,UNKNOWN PROBLEM INVESTIGATION,POINT (-86.73832 36.17512),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
249,3/3/2020 4:44:36 AM,713 RAMSEY ST,36.176340,-86.760641,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,POINT (-86.76064 36.17634),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504
254,3/3/2020 4:51:36 AM,821 RAMSEY ST,36.177137,-86.757858,ELECTRICAL HAZARD WITH OR NEAR WATER,POINT (-86.75786 36.17714),13,37206,2,NASHVILLE,75782.862116030214,221537063.58166504

### The other disp calls may have been releated to the storm but it is unk if the remainder 
### of the calls were either for a Resid or Comm area

In [285]:
eastn_zip_disp3.geometry.centroid

<ipython-input-285-35fbcd27eb9f>:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  eastn_zip_disp3.geometry.centroid

36     POINT (-86.73760 36.17422)
45     POINT (-86.72056 36.17456)
65     POINT (-86.72617 36.17551)
151    POINT (-86.74914 36.17452)
198    POINT (-86.74641 36.17531)
199    POINT (-86.75825 36.17742)
200    POINT (-86.74914 36.17452)
dtype: geometry

In [286]:
eastn_zip_disp4.geometry.centroid

<ipython-input-286-8aeb1a83d1dc>:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  eastn_zip_disp4.geometry.centroid

44     POINT (-86.75561 36.17722)
67     POINT (-86.75899 36.17666)
141    POINT (-86.75561 36.17722)
dtype: geometry

In [287]:
eastn_zip_disp.geometry.centroid

<ipython-input-287-50341fc10752>:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  eastn_zip_disp.geometry.centroid

24     POINT (-86.75702 36.17590)
25     POINT (-86.75702 36.17590)
29     POINT (-86.75899 36.17666)
130    POINT (-86.71982 36.17424)
147    POINT (-86.74985 36.17535)
152    POINT (-86.74168 36.17583)
154    POINT (-86.75041 36.17594)
155    POINT (-86.75041 36.17594)
249    POINT (-86.76064 36.17634)
dtype: geometry

In [288]:
m1 = folium.Map(
    location=[36.318245, -86.785534],
    zoom_start=10.4,

)
folium.Marker([36.17422, -86.73760], popup='1',marker_icon='cloud')
folium.Marker([36.17456, -86.72056], popup='2',marker_color='green')
m1

In [289]:
for row_index, row_values in eastn_zip_disp.iterrows():
    loc = [row_values['Latitude'], row_values['Longitude']]
    pop = str(row_values['Location'])
    marker = folium.Marker(
        location = loc, 
        popup = pop) 
    marker.add_to(m1)
    m1.save('../maps/m1.html')
    m1

FileNotFoundError: [Errno 2] No such file or directory: '../maps/m1.html'

### single_f.equals(eastn_zip_disp)

### single_f['pricesMatch?'] = np.where(single_f['Location'] == eastn_zip_disp['Location']
                               , 'True', 'False')

In [ ]:
disp_t_by_zip.head(1)

In [290]:
disp_t_by_zip.pop('IncidentDate')
disp_t_by_zip.pop('Latitude')
disp_tornado.pop('Longitude')
disp_tornado.pop('IncidentTypeDescription1')
disp_t_by_zip.pop('geometry')
disp_t_by_zip.pop('index_right')
disp_t_by_zip.pop('objectid')
disp_t_by_zip.pop('po_name')
disp_t_by_zip.pop('shape_stlength')

0      310224.91345860378
1      310224.91345860378
2      310224.91345860378
17     310224.91345860378
19     310224.91345860378
              ...
231    178783.02488886821
234    179866.56847992647
236    133803.10728562382
240    38325.180077725185
259    349164.88029162859
Name: shape_stlength, Length: 260, dtype: object

In [291]:
disp_t_by_zip

,Location,Longitude,IncidentTypeDescription1,zip,shape_starea
0,6205 COCKRILL BEND CIR,-86.894052,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,37209,1001364029.2892456
1,7337 COCKRILL BEND BLVD,-86.894978,GENERAL ALARM COMMERCIAL INDUSTRIAL BUILD,37209,1001364029.2892456
2,110 TUNE AIRPORT DR,-86.883727,STRUCTURE FIRE COMMERCIAL INDUSTRIAL,37209,1001364029.2892456
17,7337 COCKRILL BEND BLVD,-86.894978,BUILDING ENTRAPMENT UNCONFIRMED,37209,1001364029.2892456
19,7135 CENTENNIAL PL,-86.879949,INSIDE FUEL ODOR,37209,1001364029.2892456
...,...,...,...,...,...
231,200 E WEBSTER ST,-86.716657,CITIZEN ASSIST NON MEDICAL,37115,596553400.57885742
234,368 BRITISH WOODS DR,-86.654322,DIFFICULTY SPEAKING BETWEEN BREATHS,37217,517579208.08972168
236,115 LAURA AV,-86.630412,DIFFICULTY SPEAKING BETWEEN BREATHS OTHER LUNG...,37138,398431173.90905762
240,200 ATHENS WAY,-86.799250,SMOKE DETECTOR ALARM COMMERCIAL INDUSTRIAL B...,37228,47878303.581787109
259,I24 W / HICKORY HOLLOW PKWY,-86.649099,UNKNOWN STATUS:,37013,1150567551.5894165

In [ ]:
building_p.head(1)

In [ ]:
df1 = pd.DataFrame(eastn_zip_disp,columns= ['zip', 'Location'])
print(df1)

In [ ]:
df2 = pd.DataFrame(building_p,columns= ['zip', 'Location'])
print(df2)

In [ ]:
df1['Match?'] = np.isin(df1['Location'] == df2['Location'], 'True', 'False')